### ISSUE TITLE
Plugin completely broken - Overhead attack timer countdown resets/bugs out at 3

### ISSUE THREAD

**Issue by DangersClose** [ngraves95/attacktimer#23]
Please fix plugin it is great.

**Comment by ozohead** [comment]
Same with me have you found any solution?

**Comment by ngraves95** [comment]
Can you include some screenshots or gifs of what is happening? Please include other information like:
* the weapon.
* the attack style.
* a screenshot of your attacktimer config settings.

**Comment by ngraves95** [comment]
Sounds like a duplicate of https://github.com/ngraves95/attacktimer/issues/26. Closing until this can be reproed
