### ISSUE TITLE
Shattered relics variety ornament kit not working

### ISSUE THREAD

**Issue by DoctaWhom** [ngraves95/attacktimer#24]
The attack timer metronome doesnt work with items with the "Shattered relics variety ornament kit" on it such as the Rune crossbow (or), and Abyssal whip (or).

**Comment by Tchoopz** [comment]
+1 on this. The original poster and I were the ones that discovered this problem during Tombs of Amascut. My crossbow is Rune Crossbow(or) and my whip is (or) as well.

Number Above Head while Kicking
![RuneLite_AYhNooq9QV](https://github.com/ngraves95/attacktimer/assets/149325766/f73a0b21-08b9-425a-9c04-59a561d49208)

Number NOT Above Head while Bolting
![RuneLite_rS55km8gap](https://github.com/ngraves95/attacktimer/assets/149325766/1a2323f5-75e9-496b-b6ab-2e50543123a3)

**Comment by ngraves95** [comment]
Rune crossbow (or) should be fixed with https://github.com/ngraves95/attacktimer/pull/28. I have a whip (or) and things are fine for me.
