### ISSUE TITLE
COUNTER LOSING TICKS

### ISSUE THREAD

**Issue by ozohead** [ngraves95/attacktimer#26]
Not sure what happened. And multiple people are reporting the issue. But using most weapons (bowfa and trident). It will go 4 then 3 then glitch out and go back to 4... have no idea why and haven't found any solutions. It was working fine a week ago

**Comment by Ian-Fund** [comment]
@ngraves95  Are you still actively working on this plugin?

**Comment by ngraves95** [comment]
I haven't been able to repro with whip and toxic trident, for example.
1. Is this still an issue?
2. If so, can you include a gif of this happening?

**Comment by Ian-Fund** [comment]
> I haven't been able to repro with whip and toxic trident, for example.
> 
>     1. Is this still an issue?
> 
>     2. If so, can you include a gif of this happening?

The plugin just started working again about a month ago.  Not having any issues atm besides the new blowpipe ornament kit not working.

**Comment by ngraves95** [comment]
Ok - sounds like there might have been a bug and fix in one of this plugins dependencies (like ItemManager, etc). I will close this until it becomes an issue again.
