### ISSUE TITLE
Add Support For Leagues IV Relics

### ISSUE THREAD

**Issue by SaffiCauthon** [ngraves95/attacktimer#27]
Is it possible to add support for tier 4 relics in League IV?

Example relic:
![Relic Example](https://i.imgur.com/rFLkC78.png)

Crossbow attacks every 2 ticks but has a counter for 5:
![Relic In Action](https://i.imgur.com/JQ9PLy2.gif)

**Comment by ngraves95** [comment]
I don't know if there's a way to know which relics the player has chosen - if so, then it would be fairly easy to implement.

**Comment by ngraves95** [comment]
Should be added in commit 6529656b2025fc45092e3533661f8ac8df917896.

I was only able to test Archer's Embrace with ACB and dragon knives.
