### ISSUE TITLE
Crystal staff (perfected) shows as 5tick

### ISSUE THREAD

**Issue by mirkwoodia** [ngraves95/attacktimer#41]
But it's a 4tick weapon. All variations, basic and attuned as well show 5 tick

**Comment by mirkwoodia** [comment]
Sorry, first time reporting an issue, ill try to include some images

Image showing staff as a 5t weapon:
![image](https://github.com/ngraves95/attacktimer/assets/15108031/c6543703-ae45-4d6f-bcd1-fdc7ced4cc5f)

But then because its a 4t weapon, it's attacking when the tick counter shows 1
![image](https://github.com/ngraves95/attacktimer/assets/15108031/3b820825-cb5b-4021-99f1-04d9b090a5d4)

**Comment by gainzzzz** [comment]
Sang staff is doing the same thing for me now too. It just started happening yesterday so idk if something changed in the code or what?

**Comment by TimOosterom** [comment]
Same with the trident of the swamp.

**Comment by alexgermann** [comment]
#42 fixes this

**Comment by Lexer747** [comment]
Fixed by https://github.com/ngraves95/attacktimer/pull/52 (Note that Harm is still broken and a few other powered staves more fixes coming soon™️)
