### ISSUE TITLE
Timer at Kalphite Queen is totally wrong

### ISSUE THREAD

**Issue by theavish** [ngraves95/attacktimer#45]
![image](https://github.com/ngraves95/attacktimer/assets/8893033/2269313e-0873-4fd2-aae3-49f4d9f12f63)
The timer values are totally incorrect when attacking Kalphite Queen

**Comment by rqjimmy** [comment]
Not just Kalphite Queen, Keris attack timer is broken on all Kalphites. I got mine up to -20,000 before it rolled over back to -0 and started counting up again.
<img width="422" alt="keris" src="https://github.com/ngraves95/attacktimer/assets/95519941/7f0c8e21-210f-4145-bf0a-607bd1d112fc">

**Comment by Lexer747** [comment]
Yup known issue with Keris, this should now be fixed in https://github.com/ngraves95/attacktimer/pull/52
