### ISSUE TITLE
Perilous Moons weapons not implemented

### ISSUE THREAD

**Issue by CrocksRocket** [ngraves95/attacktimer#46]
Would love it if we could implement the new perilous moons weapons: 

[Eclipse atlatl](https://oldschool.runescape.wiki/w/Eclipse_atlatl)

[Dual macuahuitl](https://oldschool.runescape.wiki/w/Dual_macuahuitl)

[Blue moon spear](https://oldschool.runescape.wiki/w/Blue_moon_spear)

**Comment by Lexer747** [comment]
Fixed by https://github.com/ngraves95/attacktimer/pull/52
