### ISSUE TITLE
Add chinchompas to the list of animation ids

### ISSUE THREAD

**Issue by Kagiri12** [ngraves95/attacktimer#7]
Hey if possible could you add "Chinchompa", "Red Chinchompa" and "Black Chinchompa" ? 

Would help with chinning at Kree'arra "Armadyl" or chinning at maniacal monkeys.

**Comment by ngraves95** [comment]
PR is open to update the plugin: https://github.com/runelite/plugin-hub/pull/3804. Waiting on RL devs to merge.
